/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        display: ['Cairo', 'sans-serif'],
        body: ['Tajawal', 'sans-serif'],
      },
      colors: {
        primary: '#2f80ff',
        'on-primary': '#06101f',
        'primary-container': '#0e3b7a',
        'on-primary-container': '#dbeafe',
        secondary: '#75b7ff',
        'on-secondary': '#07111f',
        'secondary-container': '#102b4c',
        'on-secondary-container': '#d7eaff',
        tertiary: '#f4c542',
        'on-tertiary': '#111827',
        'tertiary-container': '#7c5a0b',
        'on-tertiary-container': '#fff4bf',
        background: '#06111f',
        'on-background': '#f8fbff',
        surface: '#071727',
        'on-surface': '#f8fbff',
        'surface-variant': '#172a3f',
        'on-surface-variant': '#a9bad0',
        'surface-container-lowest': '#0a1727',
        'surface-container-low': '#0d1e31',
        'surface-container': '#10263d',
        'surface-container-high': '#173451',
        'surface-container-highest': '#1e4469',
        error: '#ff6b6b',
        'on-error': '#ffffff',
        'error-container': '#641a1a',
        'on-error-container': '#ffe1e1',
        outline: '#5d7590',
        'outline-variant': '#29435d',
      },
      borderRadius: {
        'md': '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        'full': '9999px',
      },
      boxShadow: {
        'ambient': '0 18px 55px rgba(0, 0, 0, 0.28)',
        'soft': '0 12px 35px rgba(0, 0, 0, 0.2)',
        'float': '0 24px 60px rgba(0, 0, 0, 0.34)',
        'gold': '0 0 32px rgba(244, 197, 66, 0.35)',
        'blue-glow': '0 0 42px rgba(47, 128, 255, 0.24)',
      }
    },
  },
  plugins: [],
}
